version: "3.8"

services:
  client:
    build:
      context: ./
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - 80
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.services.game.loadbalancer.server.port=80

      - traefik.http.routers.game.service=game@docker
      - traefik.http.routers.game.rule=Host(`${GAME_DOMAIN}`)
      - traefik.http.routers.game.entrypoints=web
      - traefik.http.routers.game.middlewares=redirect-https

      - traefik.http.routers.game-secured.service=game@docker
      - traefik.http.routers.game-secured.entrypoints=web-secured
      - traefik.http.routers.game-secured.tls=true
      - traefik.http.routers.game-secured.rule=Host(`${GAME_DOMAIN}`)

networks:
  proxy:
    external: true
